### ISSUE TITLE
compatible with laravel 8?

### ISSUE THREAD

**Issue by masiorama** [nidrax69/YousignApiLaravel#5]
Hello, thanks for your work.
Is this package compatible with Laravel 8?
Thanks!

**Comment by masiorama** [comment]
I am trying the package on Laravel 8 and so far I was able to make it work (at least till the embed of the iframe), but I have a couple of things to share:

1. in order to make the file upload to work I had to comment line 85 of YousignApiLaravel

`if ($file_headers[0] == 'HTTP/1.1 404 Not Found') return null;`

The issue was related to array access to $file_headers...

2. I am not completely sure how webhooks should be used, for instance:

```
$client->addWebhook('member.finished', $webhookUrl . 'signature', 'GET', array(
    "X-Custom-Header" => $type . '-signature',
));
```

How am I supposed to use it? Why should I set a custom header link in the example?

ps: I am aware that I'm kinda off-topic, should I change the title?

Thanks!

**Comment by nidrax69** [comment]
Hello sorry for the delay , it's a personnal work , for my personal use, so its working on Laravel 8
I used it with AWS maybe there is some issues...

About webhook it's completely optional to add Headers. It s useful for receptionning webhook and add informations about the signature like id or whatever

**Comment by masiorama** [comment]
Thanks for your reply @nidrax69 
I managed to adapt your library for my specific scenario, using webhooks to trap responses from Yousign (as they are intended).
At the end of the day your package was a very good starting point for my needs, thanks!
